[package]
name = "app"

authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }

[[bin]]
path = "src/main.rs"
name = "rusthouse"
